# -*- coding: utf-8 -*-
import datetime as dt


from flask_test.extensions import bcrypt
from flask_test.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
)




class Player( Mo del):

    __tablename__ = 'playerrun'
    ID = Column(db.String(128), nullable=True)
    scorediffcat = Column(db.String(128), nullable=False)
    gamestate = Column(db.String(128), nullable=False)
    period = Column(db.String(128), nullable=False)
    home = Column(db.String(128), nullable=False)
    Team = Column(db.String(128), nullable=False)
    Opponent = Column(db.String(128), nullable=False)
    TOI = Column(db.String(128), nullable=False)
    ZSO = Column(db.String(128), nullable=False)
    ZSN = Column(db.String(128), nullable=False)
    ZSD = Column(db.String(128), nullable=False)
    GF = Column(db.String(128), nullable=False)
    GA = Column(db.String(128), nullable=False)
    SF = Column(db.String(128), nullable=False)
    SA = Column(db.String(128), nullable=False)
    FF = Column(db.String(128), nullable=False)
    FA = Column(db.String(128), nullable=False)
    CF = Column(db.String(128), nullable=False)
    CA = Column(db.String(128), nullable=False)
    OZF = Column(db.String(128), nullable=False)
    OZA = Column(db.String(128), nullable=False)
    GF1 = Column(db.String(128), nullable=False)
    GA1 = Column(db.String(128), nullable=False)
    SF1 = Column(db.String(128), nullable=False)
    SA1 = Column(db.String(128), nullable=False)
    FF1 = Column(db.String(128), nullable=False)
    FA1 = Column(db.String(128), nullable=False)
    CF1 = Column(db.String(128), nullable=False)
    CA1 = Column(db.String(128), nullable=False)
    GF2 = Column(db.String(128), nullable=False)
    GA2 = Column(db.String(128), nullable=False)
    SF2 = Column(db.String(128), nullable=False)
    SA2 = Column(db.String(128), nullable=False)
    FF2 = Column(db.String(128), nullable=False)
    FA2 = Column(db.String(128), nullable=False)
    CF2 = Column(db.String(128), nullable=False)
    CA2 = Column(db.String(128), nullable=False)
    GF3 = Column(db.String(128), nullable=False)
    GA3 = Column(db.String(128), nullable=False)
    SF3 = Column(db.String(128), nullable=False)
    SA3 = Column(db.String(128), nullable=False)
    FF3 = Column(db.String(128), nullable=False)
    FA3 = Column(db.String(128), nullable=False)
    CF3 = Column(db.String(128), nullable=False)
    CA3 = Column(db.String(128), nullable=False)
    GF4 = Column(db.String(128), nullable=False)
    GA4 = Column(db.String(128), nullable=False)
    SF4 = Column(db.String(128), nullable=False)
    SA4 = Column(db.String(128), nullable=False)
    FF4 = Column(db.String(128), nullable=False)
    FA4 = Column(db.String(128), nullable=False)
    CF4 = Column(db.String(128), nullable=False)
    CA4 = Column(db.String(128), nullable=False)
    SCF = Column(db.String(128), nullable=False)
    SCA = Column(db.String(128), nullable=False)
    sSCF = Column(db.String(128), nullable=False)
    sSCA = Column(db.String(128), nullable=False)
    ExpGF = Column(db.String(128), nullable=False)
    ExpGA = Column(db.String(128), nullable=False)
    TOIoff = Column(db.String(128), nullable=False)
    ZSOoff = Column(db.String(128), nullable=False)
    ZSNoff = Column(db.String(128), nullable=False)
    ZSDoff = Column(db.String(128), nullable=False)
    GFoff = Column(db.String(128), nullable=False)
    GAoff = Column(db.String(128), nullable=False)
    SFoff = Column(db.String(128), nullable=False)
    SAoff = Column(db.String(128), nullable=False)
    FFoff = Column(db.String(128), nullable=False)
    FAoff = Column(db.String(128), nullable=False)
    CFoff = Column(db.String(128), nullable=False)
    CAoff = Column(db.String(128), nullable=False)
    OZFoff = Column(db.String(128), nullable=False)
    OZAoff = Column(db.String(128), nullable=False)
    GF1off = Column(db.String(128), nullable=False)
    GA1off = Column(db.String(128), nullable=False)
    SF1off = Column(db.String(128), nullable=False)
    SA1off = Column(db.String(128), nullable=False)
    FF1off = Column(db.String(128), nullable=False)
    FA1off = Column(db.String(128), nullable=False)
    CF1off = Column(db.String(128), nullable=False)
    CA1off = Column(db.String(128), nullable=False)
    GF2off = Column(db.String(128), nullable=False)
    GA2off = Column(db.String(128), nullable=False)
    SF2off = Column(db.String(128), nullable=False)
    SA2off = Column(db.String(128), nullable=False)
    FF2off = Column(db.String(128), nullable=False)
    FA2off = Column(db.String(128), nullable=False)
    CF2off = Column(db.String(128), nullable=False)
    CA2off = Column(db.String(128), nullable=False)
    GF3off = Column(db.String(128), nullable=False)
    GA3off = Column(db.String(128), nullable=False)
    SF3off = Column(db.String(128), nullable=False)
    SA3off = Column(db.String(128), nullable=False)
    FF3off = Column(db.String(128), nullable=False)
    FA3off = Column(db.String(128), nullable=False)
    CF3off = Column(db.String(128), nullable=False)
    CA3off = Column(db.String(128), nullable=False)
    GF4off = Column(db.String(128), nullable=False)
    GA4off = Column(db.String(128), nullable=False)
    SF4off = Column(db.String(128), nullable=False)
    SA4off = Column(db.String(128), nullable=False)
    FF4off = Column(db.String(128), nullable=False)
    FA4off = Column(db.String(128), nullable=False)
    CF4off = Column(db.String(128), nullable=False)
    CA4off = Column(db.String(128), nullable=False)
    SCFoff = Column(db.String(128), nullable=False)
    SCAoff = Column(db.String(128), nullable=False)
    sSCFoff = Column(db.String(128), nullable=False)
    sSCAoff = Column(db.String(128), nullable=False)
    ExpGFoff = Column(db.String(128), nullable=False)
    ExpGAoff = Column(db.String(128), nullable=False)
    GOAL = Column(db.String(128), nullable=False)
    SHOT = Column(db.String(128), nullable=False)
    MISS = Column(db.String(128), nullable=False)
    BLOCKED_SHOT = Column(db.String(128), nullable=False)
    GOAL1 = Column(db.String(128), nullable=False)
    SHOT1 = Column(db.String(128), nullable=False)
    MISS1 = Column(db.String(128), nullable=False)
    BLOCKED_SHOT1 = Column(db.String(128), nullable=False)
    GOAL2 = Column(db.String(128), nullable=False)
    SHOT2 = Column(db.String(128), nullable=False)
    MISS2 = Column(db.String(128), nullable=False)
    BLOCKED_SHOT2 = Column(db.String(128), nullable=False)
    GOAL3 = Column(db.String(128), nullable=False)
    SHOT3 = Column(db.String(128), nullable=False)
    MISS3 = Column(db.String(128), nullable=False)
    BLOCKED_SHOT3 = Column(db.String(128), nullable=False)
    GOAL4 = Column(db.String(128), nullable=False)
    SHOT4 = Column(db.String(128), nullable=False)
    MISS4 = Column(db.String(128), nullable=False)
    BLOCKED_SHOT4 = Column(db.String(128), nullable=False)
    iSC = Column(db.String(128), nullable=False)
    isSC = Column(db.String(128), nullable=False)
    iExpG = Column(db.String(128), nullable=False)
    HIT = Column(db.String(128), nullable=False)
    PENL_TAKEN = Column(db.String(128), nullable=False)
    TAKE = Column(db.String(128), nullable=False)
    GIVE = Column(db.String(128), nullable=False)
    FAC_WIN = Column(db.String(128), nullable=False)
    BLOCK = Column(db.String(128), nullable=False)
    ASSIST = Column(db.String(128), nullable=False)
    HIT_TAKEN = Column(db.String(128), nullable=False)
    PENL_DRAWN = Column(db.String(128), nullable=False)
    FAC_LOSE = Column(db.String(128), nullable=False)
    ASSIST_2 = Column(db.String(128), nullable=False)
    season = Column(db.String(128), nullable=False)
    gcode = Column(db.String(128), nullable=False)
    tCF60 = Column(db.String(128), nullable=False)
    tCA60 = Column(db.String(128), nullable=False)
    tFF60 = Column(db.String(128), nullable=False)
    tFA60 = Column(db.String(128), nullable=False)
    tTOI60 = Column(db.String(128), nullable=False)
    cCF60 = Column(db.String(128), nullable=False)
    cCA60 = Column(db.String(128), nullable=False)
    cFF60 = Column(db.String(128), nullable=False)
    cFA60 = Column(db.String(128), nullable=False)
    cTOI60 = Column(db.String(128), nullable=False)
    Date = Column(db.String(128), nullable=False)


    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)